//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompiledViews.Mvc3Test.Views.Shared {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    
    public class _Layout : CompiledViews.Mvc.CompiledViewPage<dynamic> {
        
#line hidden

        
        public _Layout() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>");


      Write(ViewBag.Title);

WriteLiteral("</title>\r\n    <link href=\"");


           Write(Url.Content("~/Content/Site.css"));

WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"");


            Write(Url.Content("~/Scripts/jquery-1.4.4.min.js"));

WriteLiteral("\" type=\"text/javascript\"></script>\r\n</head>\r\n\r\n<body>\r\n<h1>Body</h1>\r\n    ");


Write(RenderBody());

WriteLiteral("\r\n    <h1>Section</h1>\r\n    ");


Write(RenderSection("Section1", false));

WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
