//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompiledViews.Mvc3Test.Views.Shared {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.WebPages.Html;
    
    
    public class Error : CompiledViews.Mvc.CompiledViewPage<object> {
        
#line hidden

        
        public Error() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

  
    Layout = null;


WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>Error</title>\r\n</head>\r\n<body>\r\n   " +
" <h2>\r\n        Sorry, an error occurred while processing your request.\r\n    </h2" +
">\r\n</body>\r\n</html>");


        }
    }
}
